#!/bin/bash

export NBLOSS="ENTROPY"
#export NBLOSS="QUADRATIC"

export LEARNDIAG=1

export SHAPE="DIAG"

#export PRE=621
export PRE=612

#export TRAINCONFIGNAME="TrainAllTks-EvalAllTks-NoReweight"
export TRAINCONFIGNAME="TrainAllTks-EvalAllTks-ReweightRICH2"
#export TRAINCONFIGNAME="test"

export TKPRESEL="RejGhosts"

ssh -f lxplus421 "${CHARGEDPROTOANNPIDTEACHERROOT}/training/Run.sh -TRAINOPTS ${TRAINCONFIGNAME} -MVATYPE NB -NBMETHOD BFGS   -NBLOSS ${NBLOSS} -NBPRE ${PRE} -NBLEARNDIAG ${LEARNDIAG} -NBSHAPE ${SHAPE} -CONFIGNAME ${TKPRESEL}-NoGECs &"
ssh -f lxplus422 "${CHARGEDPROTOANNPIDTEACHERROOT}/training/Run.sh -TRAINOPTS ${TRAINCONFIGNAME} -MVATYPE NB -NBMETHOD NOBFGS -NBLOSS ${NBLOSS} -NBPRE ${PRE} -NBLEARNDIAG ${LEARNDIAG} -NBSHAPE ${SHAPE} -CONFIGNAME ${TKPRESEL}-NoGECs &"

export TKPRESEL="NoPreSels"

ssh -f lxplus432 "${CHARGEDPROTOANNPIDTEACHERROOT}/training/Run.sh -TRAINOPTS ${TRAINCONFIGNAME} -MVATYPE NB -NBMETHOD BFGS   -NBLOSS ${NBLOSS} -NBPRE ${PRE} -NBLEARNDIAG ${LEARNDIAG} -NBSHAPE ${SHAPE} -CONFIGNAME ${TKPRESEL}-NoGECs &"
ssh -f lxplus433 "${CHARGEDPROTOANNPIDTEACHERROOT}/training/Run.sh -TRAINOPTS ${TRAINCONFIGNAME} -MVATYPE NB -NBMETHOD NOBFGS -NBLOSS ${NBLOSS} -NBPRE ${PRE} -NBLEARNDIAG ${LEARNDIAG} -NBSHAPE ${SHAPE} -CONFIGNAME ${TKPRESEL}-NoGECs &"

exit 0
