#!/bin/bash

export CHARGEDPROTOANNPIDTEACHERROOT=${PWD}/../
export RUN=${CHARGEDPROTOANNPIDTEACHERROOT}/training/Run.sh

export MLPHIDDENLAYERSCALEF=1.2

export TMVAVARTRANSFORM="Norm"
#export TMVAVARTRANSFORM="Decorrelate"
#export TMVAVARTRANSFORM="Decorrelate,Norm"
#export TMVAVARTRANSFORM="None"

export TMVAMLPESTIMATORTYPE="CE"
#export TMVAMLPESTIMATORTYPE="MSE"

#export TMVAMLPMETHOD="BP"
#export TMVAMLPNCYCLES="750"

export TMVAMLPMETHOD="BFGS"
export TMVAMLPNCYCLES="100"

#for TRAINCONFIGNAME in "test"; do
for TRAINCONFIGNAME in "TrainAllTks-EvalAllTks-ReweightRICH2" ; do
#for TRAINCONFIGNAME in "TrainAllTks-EvalAllTks-NoReweight" "TrainAllTks-EvalBTks-NoReweight" "TrainBTks-EvalBTks-NoReweight" "TrainBTks-EvalAllTks-NoReweight" ; do
 for TMVAMLPNEURONTYPE in "tanh" "sigmoid"; do
  for TKPRESEL in "NoPreSels" "RejGhosts"; do
 #for TMVAMLPNEURONTYPE in "tanh"; do
  #for TKPRESEL in "RejGhosts"; do

   $RUN -TRAINOPTS ${TRAINCONFIGNAME} -CONFIGNAME ${TKPRESEL}-NoGECs -TMVAMLPNCYCLES $TMVAMLPNCYCLES -MVATYPE TMVA -TMVAMETHOD MLP -TMVAVARTRANSFORM $TMVAVARTRANSFORM -TMVAMLPNEURONTYPE $TMVAMLPNEURONTYPE -TMVAMLPESTIMATORTYPE $TMVAMLPESTIMATORTYPE -TMVAMLPMETHOD $TMVAMLPMETHOD -MLPHIDDENLAYERSCALEF $MLPHIDDENLAYERSCALEF

  done
 done
done

exit 0
